const SET_ALERT = 'SET_ALERT';
const REMOVE_ALERT = "REMOVE_ALERT";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAILED = "REGISTER_FAILED";
const USER_LOADED = "USER_LOADED";
const AUTH_ERROR = "AUTH_ERROR";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";
const LOGOUT = "LOGOUT"
const GET_PROFILE = "GET_PROFILE"
const GET_PROFILES = "GET_PROFILES"
const CLEAR_PROFILE = "CLEAR_PROFILE"
const PROFILE_ERROR = "PROFILE_ERROR"
const UPDATE_PROFILE = "UPDATE_PROFILE"
export {
	SET_ALERT,REMOVE_ALERT,REGISTER_FAILED,REGISTER_SUCCESS,USER_LOADED,AUTH_ERROR,
	LOGIN_FAIL,LOGIN_SUCCESS,LOGOUT,GET_PROFILE,PROFILE_ERROR,CLEAR_PROFILE,UPDATE_PROFILE,GET_PROFILES
}